# Generated by Django 6.0.6 on 2026-06-20 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='For anonymous users — linked to ChatSession.session_key', max_length=100, null=True)),
                ('action', models.CharField(choices=[('view', 'Product Viewed'), ('search', 'Product Searched'), ('cart_add', 'Added to Cart'), ('wishlist', 'Added to Wishlist'), ('purchase', 'Purchased')], max_length=20)),
                ('entity_type', models.CharField(help_text='e.g. product, category, search_query', max_length=50)),
                ('entity_id', models.IntegerField(blank=True, help_text='ID of the entity (product_id, category_id etc.)', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Extra context: search query text, price filter, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_behaviors', to='stores.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='behaviors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_behavior',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'action', 'created_at'], name='customer_be_store_i_5b511d_idx'), models.Index(fields=['user', 'action'], name='customer_be_user_id_a9388a_idx'), models.Index(fields=['session_key'], name='customer_be_session_b75d39_idx')],
            },
        ),
    ]
