# Generated by Django 6.0.6 on 2026-07-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_add_priority_and_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={},
        ),
        migrations.AlterModelTable(
            name='complaint',
            table=None,
        ),
    ]
