# Generated by Django 6.0.6 on 2026-07-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
