# Generated by Django 6.0.6 on 2026-06-20 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('both', 'Both')], max_length=20)),
                ('caption', models.TextField()),
                ('hashtags', models.TextField(help_text='Space-separated hashtags e.g. #Samsung #GalaxyS25')),
                ('image_url', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='When to publish — set after admin approval', null=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='Actual time of successful publish', null=True)),
                ('ig_post_id', models.CharField(blank=True, help_text='Instagram post ID after successful publish', max_length=200, null=True)),
                ('fb_post_id', models.CharField(blank=True, help_text='Facebook post ID after successful publish', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created/approved this post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, help_text='Product this post is about — null for manual posts', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='stores.store')),
            ],
            options={
                'db_table': 'social_posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialPostAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('reach', models.IntegerField(default=0, help_text='Number of unique accounts that saw this post')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='social.socialpost')),
            ],
            options={
                'db_table': 'social_post_analytics',
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook')], max_length=20)),
                ('account_name', models.CharField(max_length=200)),
                ('access_token', models.TextField(help_text='Encrypted access token — never store plain text')),
                ('token_expiry', models.DateTimeField(blank=True, help_text='When the access token expires — used for renewal alerts', null=True)),
                ('page_id', models.CharField(blank=True, help_text='Facebook Page ID or Instagram Business Account ID', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='stores.store')),
            ],
            options={
                'db_table': 'social_accounts',
                'unique_together': {('store', 'platform')},
            },
        ),
    ]
