# Generated by Django 6.0.6 on 2026-06-21 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('current_flow', models.CharField(blank=True, help_text='e.g. add_product, checkout', max_length=100, null=True)),
                ('state_data', models.JSONField(blank=True, help_text='Collected fields so far in the current flow', null=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'whatsapp_sessions',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('message', models.TextField()),
                ('is_admin', models.BooleanField(default=False, help_text='True if this number is a registered admin')),
                ('metadata', models.JSONField(blank=True, help_text='Raw payload, intent, tool calls etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_logs', to='stores.store')),
            ],
            options={
                'db_table': 'whatsapp_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'created_at'], name='whatsapp_lo_phone_n_823b1f_idx')],
            },
        ),
    ]
