# Generated by Django 6.0.6 on 2026-07-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_verified_emailverification_twofactorauth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='access_jti',
            field=models.CharField(blank=True, default='', help_text='JWT ID of the access token issued at the same login, used to detect the current session', max_length=255),
        ),
    ]
