# Generated by Django 6.0.6 on 2026-06-20 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='stores.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=10)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, help_text='Structured data: product cards, order info, cart state etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.chatsession')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='e.g. create_product, update_order_status, delete_category', max_length=100)),
                ('entity', models.CharField(help_text='e.g. product, order, category, inventory', max_length=50)),
                ('entity_id', models.IntegerField(blank=True, help_text='ID of the affected record', null=True)),
                ('old_data', models.JSONField(blank=True, help_text='Snapshot of record BEFORE the change', null=True)),
                ('new_data', models.JSONField(blank=True, help_text='Snapshot of record AFTER the change', null=True)),
                ('ip_address', models.CharField(blank=True, help_text='IP address of the request — null for WhatsApp actions', max_length=50, null=True)),
                ('source', models.CharField(default='web', help_text='Where the action came from: web, whatsapp', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='stores.store')),
                ('user', models.ForeignKey(blank=True, help_text='Admin who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'entity', 'created_at'], name='audit_logs_store_i_711edd_idx'), models.Index(fields=['user', 'created_at'], name='audit_logs_user_id_fbfd51_idx')],
            },
        ),
    ]
